### PR TITLE
zenodo: Add .zenodo.json

### PR DESCRIPTION
**Pull request by jdemel**
It should be really simple to do releases with:
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

You might want to check if your details are correct.

### CODE REVIEW

**Comment by nick-schwarzenberg** [comment]
Thanks for referring that article! As far as I can tell, having linked Zenodo to GitHub, creating a release will now be enough to create a DOI. Is the file .zenodo.json still needed, or does it just provide some convenience metadata to display on Zenodo?

In any case, I think you might have used a .zenodo.json of one of your repositories and forgot to remove yourself from the list of creators. Also, please undo the changes to the main README as they are unnecessary for the release.

**Comment by jdemel** [comment]
I reverted the README changes.

In most cases every person with a commit shows up in the creators list. That's how I manage this usually. I can remove my name from the list if this is your preference.

The `.zenodo.json` makes things nicer. e.g. the links show up, keywords, additional author info (ORCID, affiliation), etc. 

**EDIT**: In most cases, file copyright notices use the author name, sometimes +email, You may want to change that.

**Comment by nick-schwarzenberg** [comment]
> I reverted the README changes.

Thank you.

> In most cases every person with a commit shows up in the creators list.

I see your point. However, having experienced people sneaking in their names without having contributed anything relevant, I feel less enthusiastic about it. The field is called "creators" instead of "contributors"; adding people with minor contributions appears rather misleading to me. Would you be OK with removing yourself from the list for now? I'd be happy to see your name included once you contribute more than metadata.

> In most cases, file copyright notices use the author name, sometimes +email, You may want to change that.

You're right, I'll take care of this before creating the release.

(Edited to fix formatting)

**Comment by jdemel** [comment]
Alright. Done.

**Pull request merged**
